### ISSUE TITLE
Remote theme

### ISSUE THREAD

**Issue by spretosg** [spretosg/GB_page#4]
remote theme einbinden

**Comment by ureber** [comment]
In der aktuellen Version läuft Remote theme bei mir lokal, auf Github sieht es aber nach wie vor traurig aus. Affaire à suivre...

**Comment by ureber** [comment]
OK, das Remote theme läuft (aktuell noch auf einem Fork von mir). Das Problem sind jetzt noch die Bilder. Irgendwie stimmt etwas mit den Pfaden (url, baseurl) nicht, bzw. passt noch nicht mit Github. Das müssen wir noch sortieren.

**Comment by ureber** [comment]
Bilder-Problem ist gelöst. Es braucht den Pfad /GB_page/img/bild.jpg, damit sie richtig angezeigt werden, nicht nur /img/bild.jpg. Jetzt nur noch in _config.yml das Repo mit dem Fork vom Theme anpassen.
